Repository bridgetownrb/bridgetown, pull requests merged in 2020-10, with the labels that each got.

#148 feat: alias pager to paginator
  bridgetown-core/lib/bridgetown-core/page.rb
  bridgetown-core/lib/bridgetown-core/renderer.rb
  bridgetown-core/lib/bridgetown-core/ruby_template_view.rb
  bridgetown-paginate/lib/bridgetown-paginate/pagination_model.rb
Labels: enhancement

#150 Add reading_time filter/helper
  bridgetown-core/lib/bridgetown-core/filters.rb
  bridgetown-core/test/test_filters.rb
  bridgetown-website/src/_data/bridgetown_filters.yml
Labels: enhancement

#158 Use HashWithDotAccess::Hash for all data/config hashes
  bridgetown-builder/lib/bridgetown-builder/document.rb
  bridgetown-builder/lib/bridgetown-builder/plugin.rb
  bridgetown-core/benchmark/indifferent-access.rb
  bridgetown-core/bridgetown-core.gemspec
  bridgetown-core/lib/bridgetown-core.rb
  bridgetown-core/lib/bridgetown-core/concerns/site/content.rb
  bridgetown-core/lib/bridgetown-core/concerns/site/processable.rb
  bridgetown-core/lib/bridgetown-core/concerns/validatable.rb
  bridgetown-core/lib/bridgetown-core/configuration.rb
  bridgetown-core/lib/bridgetown-core/document.rb
  bridgetown-core/lib/bridgetown-core/readers/data_reader.rb
  bridgetown-core/lib/bridgetown-core/readers/defaults_reader.rb
  bridgetown-core/lib/bridgetown-core/utils/ruby_exec.rb
  bridgetown-core/test/test_configuration.rb
  bridgetown-core/test/test_data_reader.rb
  bridgetown-website/src/_docs/erb-and-beyond.md
  bridgetown-website/src/_docs/front-matter.md
Labels: enhancement

#168 Site documents array should exclude static files
  bridgetown-core/lib/bridgetown-core/collection.rb
  bridgetown-core/lib/bridgetown-core/concerns/site/content.rb
  bridgetown-core/lib/bridgetown-core/concerns/site/writable.rb
  bridgetown-core/lib/bridgetown-core/drops/site_drop.rb
  bridgetown-core/lib/bridgetown-core/reader.rb
  bridgetown-core/lib/bridgetown-core/readers/post_reader.rb
  bridgetown-core/lib/bridgetown-core/site.rb
  bridgetown-core/test/test_document.rb
  bridgetown-core/test/test_site.rb
  bridgetown-website/src/_data/bridgetown_variables.yml
Labels: bug

#155 build: add matrix testing for Ruby
  .github/workflows/build.yml
Labels: ruby3

#163 False value supported for no layouts
  bridgetown-core/features/rendering.feature
  bridgetown-core/lib/bridgetown-core/concerns/layout_placeable.rb
  bridgetown-website/src/_docs/front-matter.md
  bridgetown-website/src/_docs/layouts.md
Labels: bug

#169 Render objects in Ruby templates
  CHANGELOG.md
  bridgetown-builder/test/test_helpers_dsl.rb
  bridgetown-core/lib/bridgetown-core/concerns/site/extensible.rb
  bridgetown-core/lib/bridgetown-core/converters/erb_templates.rb
  bridgetown-core/lib/bridgetown-core/filters.rb
  bridgetown-core/lib/bridgetown-core/plugin_manager.rb
  bridgetown-core/lib/bridgetown-core/ruby_template_view.rb
  bridgetown-core/lib/bridgetown-core/watcher.rb
  bridgetown-core/test/plugin_content/components/example/override_component.rb
  bridgetown-core/test/source/plugins/block_helper.rb
  bridgetown-core/test/source/src/_components/example/override_component.rb
  bridgetown-core/test/source/src/_components/ruby_component.rb
  bridgetown-core/test/source/src/_layouts/erblayout.erb
  bridgetown-core/test/source/src/page_using_erb.erb
  bridgetown-core/test/test_erb.rb
  bridgetown-website/src/_docs/erb-and-beyond.md
  bridgetown-website/src/_docs/plugins/helpers.md
Labels: enhancement

#157 Configurable template engines on a per-site or per-document basis (WIP)
  bridgetown-core/features/hooks.feature
  bridgetown-core/features/layout_data.feature
  bridgetown-core/features/step_definitions.rb
  bridgetown-core/features/template_engines.feature
  bridgetown-core/lib/bridgetown-core.rb
  bridgetown-core/lib/bridgetown-core/concerns/liquid_renderable.rb
  bridgetown-core/lib/bridgetown-core/concerns/site/renderable.rb
  bridgetown-core/lib/bridgetown-core/converter.rb
  bridgetown-core/lib/bridgetown-core/converters/erb_templates.rb
  bridgetown-core/lib/bridgetown-core/converters/liquid_templates.rb
  bridgetown-core/lib/bridgetown-core/converters/markdown.rb
  bridgetown-core/lib/bridgetown-core/drops/unified_payload_drop.rb
  bridgetown-core/lib/bridgetown-core/excerpt.rb
  bridgetown-core/lib/bridgetown-core/liquid_renderer.rb
  bridgetown-core/lib/bridgetown-core/renderer.rb
  bridgetown-core/lib/bridgetown-core/ruby_template_view.rb
  bridgetown-core/test/test_excerpt.rb
  bridgetown-core/test/test_page.rb
  bridgetown-core/test/test_tags.rb
  bridgetown-website/plugins/builders/liquid_book.rb
  bridgetown-website/src/_layouts/default.html
  bridgetown-website/src/plugins.liquid
Labels: enhancement

#162 Support per-document locale permalinks and config
  bridgetown-core/features/permalinks.feature
  bridgetown-core/lib/bridgetown-core/concerns/site/renderable.rb
  bridgetown-core/lib/bridgetown-core/document.rb
  bridgetown-core/lib/bridgetown-core/drops/url_drop.rb
Labels: enhancement

#174 Convert ERB and Beyond docs to ERB and use capture helper for liquid_render
  .rubocop.yml
  bridgetown-builder/.rubocop.yml
  bridgetown-core/lib/bridgetown-core/concerns/site/processable.rb
  bridgetown-core/lib/bridgetown-core/ruby_template_view.rb
  bridgetown-core/lib/bridgetown-core/tags/render_content.rb
  bridgetown-paginate/.rubocop.yml
  bridgetown-paginate/lib/bridgetown-paginate/pagination_generator.rb
  bridgetown-paginate/lib/bridgetown-paginate/pagination_indexer.rb
  bridgetown-paginate/lib/bridgetown-paginate/pagination_model.rb
  bridgetown-paginate/lib/bridgetown-paginate/pagination_page.rb
  bridgetown-paginate/lib/bridgetown-paginate/paginator.rb
  bridgetown-website/plugins/builders/tags.rb
  bridgetown-website/src/_docs/erb-and-beyond.md
Labels: bug, documentation
