Repository bridgetownrb/bridgetown, pull requests merged in 2020-07, with the labels that each got.

#84 Reducing animation for users who prefer reduced motion
  bridgetown-website/frontend/javascript/index.js
Labels: documentation, enhancement

#80 Remove the Convertible concern and refactor into additional concerns
  bridgetown-core/lib/bridgetown-core.rb
  bridgetown-core/lib/bridgetown-core/concerns/convertible.rb
  bridgetown-core/lib/bridgetown-core/concerns/data_accessible.rb
  bridgetown-core/lib/bridgetown-core/concerns/layout_placeable.rb
  bridgetown-core/lib/bridgetown-core/concerns/liquid_renderable.rb
  bridgetown-core/lib/bridgetown-core/concerns/publishable.rb
  bridgetown-core/lib/bridgetown-core/concerns/validatable.rb
  bridgetown-core/lib/bridgetown-core/document.rb
  bridgetown-core/lib/bridgetown-core/excerpt.rb
  bridgetown-core/lib/bridgetown-core/layout.rb
  bridgetown-core/lib/bridgetown-core/page.rb
  bridgetown-core/lib/bridgetown-core/regenerator.rb
  bridgetown-core/test/test_page.rb
  bridgetown-core/test/test_page_without_a_file.rb
  bridgetown-core/test/test_regenerator.rb
  bridgetown-core/test/test_validatable.rb
Labels: process

#85 Feature/yard documentation
  .gitignore
  Gemfile
  bridgetown-core/Rakefile
  bridgetown-core/lib/bridgetown-core/concerns/site/configurable.rb
  bridgetown-core/lib/bridgetown-core/concerns/site/content.rb
  bridgetown-core/lib/bridgetown-core/concerns/site/extensible.rb
  bridgetown-core/lib/bridgetown-core/concerns/site/processable.rb
  bridgetown-core/lib/bridgetown-core/concerns/site/renderable.rb
  bridgetown-core/lib/bridgetown-core/concerns/site/writable.rb
Labels: documentation, enhancement

#79 ERB/Slim/Haml template support
  bridgetown-core/bridgetown-core.gemspec
  bridgetown-core/lib/bridgetown-core.rb
  bridgetown-core/lib/bridgetown-core/configuration.rb
  bridgetown-core/lib/bridgetown-core/converter.rb
  bridgetown-core/lib/bridgetown-core/converters/erb_templates.rb
  bridgetown-core/lib/bridgetown-core/converters/markdown.rb
  bridgetown-core/lib/bridgetown-core/converters/smartypants.rb
  bridgetown-core/lib/bridgetown-core/filters.rb
  bridgetown-core/lib/bridgetown-core/layout.rb
  bridgetown-core/lib/bridgetown-core/renderer.rb
  bridgetown-core/lib/bridgetown-core/ruby_template_view.rb
  bridgetown-core/test/source/src/_components/test_component.html
  bridgetown-core/test/source/src/_layouts/erblayout.erb
  bridgetown-core/test/source/src/_partials/testing/_partials.erb
  bridgetown-core/test/source/src/page_using_erb.erb
  bridgetown-core/test/test_erb.rb
  bridgetown-core/test/test_filters.rb
  bridgetown-core/test/test_layout_reader.rb
  bridgetown-core/test/test_site.rb
  bridgetown-website/src/authors/index.json.erb
Labels: enhancement, question

#99 feat(tags): Adding a class_map tag
  bridgetown-core/lib/bridgetown-core/tags/class_map.rb
  bridgetown-core/test/test_tags.rb
Labels: enhancement

#96 Feat: webpack manifest errors
  bridgetown-core/features/webpack_path_tag.feature
  bridgetown-core/lib/bridgetown-core/errors.rb
  bridgetown-core/lib/bridgetown-core/tags/webpack_path.rb
Labels: enhancement

#102 Documentation for ERB templates
  bridgetown-website/src/_docs/erb-and-beyond.md
  bridgetown-website/src/_docs/jamstack.md
  bridgetown-website/src/_docs/liquid.md
  bridgetown-website/src/_docs/philosophy.md
  bridgetown-website/src/_docs/variables.md
Labels: documentation

#115 Call GitHub API to determain default branch name
  bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb
  bridgetown-core/lib/bridgetown-core/utils.rb
  bridgetown-core/test/test_utils.rb
Labels: enhancement

#114 Fix the "add_yarn_for_gem" action
  bridgetown-core/lib/bridgetown-core/plugin_manager.rb
Labels: bug
