Repository bridgetownrb/bridgetown, pull requests merged in 2020-09, with the labels that each got.

#127 Switch from AwesomePrint to AmazingPrint
  bridgetown-core/bridgetown-core.gemspec
  bridgetown-core/lib/bridgetown-core/commands/console.rb
Labels: dependencies

#131 First pass at implementing site locales and translations
  bridgetown-core/lib/bridgetown-core/concerns/site/localizable.rb
  bridgetown-core/lib/bridgetown-core/configuration.rb
  bridgetown-core/lib/bridgetown-core/drops/site_drop.rb
  bridgetown-core/lib/bridgetown-core/ruby_template_view.rb
  bridgetown-core/lib/bridgetown-core/site.rb
  bridgetown-core/lib/bridgetown-core/tags/t.rb
Labels: enhancement

#101 Provide a Liquid find tag as easier alternative to where_exp
  bridgetown-core/lib/bridgetown-core/filters.rb
  bridgetown-core/lib/bridgetown-core/filters/condition_helpers.rb
  bridgetown-core/lib/bridgetown-core/tags/find.rb
  bridgetown-core/test/test_tags.rb
  bridgetown-website/src/_layouts/docs.liquid
Labels: enhancement

#139 Process data cascade for folder-based frontmatter defaults
  bridgetown-core/lib/bridgetown-core.rb
  bridgetown-core/lib/bridgetown-core/concerns/site/configurable.rb
  bridgetown-core/lib/bridgetown-core/frontmatter_defaults.rb
  bridgetown-core/lib/bridgetown-core/reader.rb
  bridgetown-core/lib/bridgetown-core/readers/collection_reader.rb
  bridgetown-core/lib/bridgetown-core/readers/data_reader.rb
  bridgetown-core/lib/bridgetown-core/readers/defaults_reader.rb
  bridgetown-core/lib/bridgetown-core/readers/layout_reader.rb
  bridgetown-core/lib/bridgetown-core/readers/page_reader.rb
  bridgetown-core/lib/bridgetown-core/readers/post_reader.rb
  bridgetown-core/lib/bridgetown-core/readers/static_file_reader.rb
  bridgetown-core/test/source/src/_posts/_defaults.yml
  bridgetown-core/test/source/src/_posts/es/_defaults.yml
  bridgetown-core/test/source/src/_posts/es/further/2020-09-10-further-nested.md
  bridgetown-core/test/test_defaults_reader.rb
  bridgetown-core/test/test_filters.rb
  bridgetown-core/test/test_front_matter_defaults.rb
  bridgetown-core/test/test_generated_site.rb
  bridgetown-core/test/test_site.rb
  bridgetown-website/bridgetown.config.yml
  bridgetown-website/src/_defaults.yml
  bridgetown-website/src/_docs/_defaults.yml
  bridgetown-website/src/_posts/_defaults.yml
  bridgetown-website/src/_posts/drafts/_defaults.yml
Labels: enhancement

#149 docs: add graphtown to the documentation
  bridgetown-website/src/_docs/plugins/external-apis.md
Labels: documentation
