Repository bridgetownrb/bridgetown, pull requests merged in 2021-07, with the labels that each got.

#346 docs(components): Document how the ActionView helpers allowlist works
  bridgetown-website/src/_docs/components/ruby.md
Labels: documentation

#348 Configure sites in subfolders via base_path, not baseurl
  bridgetown-core/lib/bridgetown-core/commands/concerns/build_options.rb
  bridgetown-core/lib/bridgetown-core/commands/serve.rb
  bridgetown-core/lib/bridgetown-core/concerns/site/configurable.rb
  bridgetown-core/lib/bridgetown-core/configuration.rb
  bridgetown-core/lib/bridgetown-core/drops/site_drop.rb
  bridgetown-core/lib/bridgetown-core/filters/url_filters.rb
  bridgetown-core/lib/bridgetown-core/resource/destination.rb
  bridgetown-core/lib/bridgetown-core/resource/permalink_processor.rb
  bridgetown-core/lib/bridgetown-core/site.rb
  bridgetown-core/lib/bridgetown-core/static_file.rb
  bridgetown-core/lib/bridgetown-core/utils.rb
  bridgetown-core/lib/site_template/bridgetown.config.yml
  bridgetown-core/lib/site_template/src/_data/site_metadata.yml
  bridgetown-core/test/test_filters.rb
  bridgetown-core/test/test_site.rb
  bridgetown-website/src/_data/bridgetown_filters.yml
  bridgetown-website/src/_data/site_metadata.yml
  bridgetown-website/src/_docs/configuration/options.md
  bridgetown-website/src/_docs/deployment.md
  bridgetown-website/src/_docs/resources.md
Labels: enhancement

#344 Resource extension API along with basic summary feature
  bridgetown-core/lib/bridgetown-core.rb
  bridgetown-core/lib/bridgetown-core/drops/resource_drop.rb
  bridgetown-core/lib/bridgetown-core/resource/base.rb
  bridgetown-core/test/resources/plugins/resource_extension.rb
  bridgetown-core/test/resources/src/top-level-page.md
  bridgetown-core/test/test_resource.rb
  bridgetown-website/src/_docs/resources.md
Labels: resource engine
